1

diff --git a/.github/workflows/dev-deployment.yaml b/.github/workflows/dev-deployment.yaml
--- a/.github/workflows/dev-deployment.yaml
+++ b/.github/workflows/dev-deployment.yaml
@@ -32,24 +32,24 @@ jobs:
           file_path: dev/application.yaml
           main_key: spec
 
-      - name: Trigger ArgoCD Sync
-        env:
-          ARGOCD_SERVER: ${{ vars.ARGOCD_SERVER }}
-          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
-          ARGOCD_APP_NAME: ${{ vars.ARGOCD_DEV_APP_NAME }}
-        run: |
-          response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
-            -H "Authorization: Bearer $ARGOCD_TOKEN" \
-            -H "Content-Type: application/json" \
-            "$ARGOCD_SERVER/api/v1/applications/$ARGOCD_APP_NAME/sync" \
-            -d '{}')
-
-          if [ "$response_code" -ne 200 ]; then
-            echo "Error: ArgoCD sync failed with HTTP status code $response_code"
-            exit 1
-          else
-            echo "ArgoCD sync triggered successfully"
-          fi
+#      - name: Trigger ArgoCD Sync
+#        env:
+#          ARGOCD_SERVER: ${{ vars.ARGOCD_SERVER }}
+#          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
+#          ARGOCD_APP_NAME: ${{ vars.ARGOCD_DEV_APP_NAME }}
+#        run: |
+#          response_code=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
+#            -H "Authorization: Bearer $ARGOCD_TOKEN" \
+#            -H "Content-Type: application/json" \
+#            "$ARGOCD_SERVER/api/v1/applications/$ARGOCD_APP_NAME/sync" \
+#            -d '{}')
+#
+#          if [ "$response_code" -ne 200 ]; then
+#            echo "Error: ArgoCD sync failed with HTTP status code $response_code"
+#            exit 1
+#          else
+#            echo "ArgoCD sync triggered successfully"
+#          fi
 
       - name: Slack Notification
         if: success()
